import type { Client } from "@/types";

const users = {
  u1: { id: "u1", name: "Admin", surname: "User" },
  u2: { id: "u2", name: "Sarah", surname: "Connor" },
  u3: { id: "u3", name: "Mike", surname: "Taylor" },
};

export const getClientsTestApi = async (): Promise<Client[]> => {
  return Promise.resolve([
    {
      id: "1",
      name: "John",
      surname: "Doe",
      email: "john@mail.com",
      phone: "+380000000000",
      status: "NEW",
      notes: "First contact",
      // notes: [
      //   { id: "1", description: "mdewd,ekwdneuwn cuwen cunweuicnewuicbw" },
      //   {
      //     id: "2",
      //     description: "dnuewbdybwe dcewybc eywbcu ewcybew ucbew bcyw be",
      //   },
      // ],
      // orderIndex: "1",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "2",
      name: "Jane",
      surname: "Smith",
      email: "jane@mail.com",
      phone: "+380000000001",
      status: "IN_PROGRESS",
      notes: "Waiting for reply",
      // orderIndex: "2",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "3",
      name: "Michael",
      surname: "Brown",
      email: "michael@mail.com",
      phone: "+380000000002",
      status: "DONE",
      notes: "Deal closed",
      // orderIndex: "3",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "4",
      name: "Emily",
      surname: "Johnson",
      email: "emily@mail.com",
      phone: "+380000000003",
      status: "NEW",
      notes: "Requested demo",
      // orderIndex: "4",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "5",
      name: "Daniel",
      surname: "Wilson",
      email: "daniel@mail.com",
      phone: "+380000000004",
      status: "IN_PROGRESS",
      notes: "Negotiation stage",
      // orderIndex: "5",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "6",
      name: "Olivia",
      surname: "Martinez",
      email: "olivia@mail.com",
      phone: "+380000000005",
      status: "NEW",
      notes: "Left contact form",
      // orderIndex: "6",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "7",
      name: "William",
      surname: "Anderson",
      email: "william@mail.com",
      phone: "+380000000006",
      status: "DONE",
      notes: "Signed contract",
      // orderIndex: "7",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "8",
      name: "Sophia",
      surname: "Lee",
      email: "sophia@mail.com",
      phone: "+380000000007",
      status: "IN_PROGRESS",
      notes: "Preparing proposal",
      // orderIndex: "8",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "9",
      name: "James",
      surname: "Walker",
      email: "james@mail.com",
      phone: "+380000000008",
      status: "NEW",
      notes: "Cold lead",
      // orderIndex: "9",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "10",
      name: "Isabella",
      surname: "Harris",
      email: "isabella@mail.com",
      phone: "+380000000009",
      status: "DONE",
      notes: "Repeat client",
      // orderIndex: "10",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
};
