import type { Client } from "@/types";

const users = {
  u1: { id: "u1", first_name: "Admin", last_name: "User" },
  u2: { id: "u2", first_name: "Sarah", last_name: "Connor" },
  u3: { id: "u3", first_name: "Mike", last_name: "Taylor" },
};

export const getClientsTestApi = async (): Promise<Client[]> => {
  return Promise.resolve([
    {
      id: "1",
      first_name: "John",
      last_name: "Doe",
      email: "john@mail.com",
      phone: "+380000000000",
      status: "new",
      comment: "First contact",
      notes: [
        { id: "1", description: "mdewd,ekwdneuwn cuwen cunweuicnewuicbw" },
        {
          id: "2",
          description: "dnuewbdybwe dcewybc eywbcu ewcybew ucbew bcyw be",
        },
      ],
      orderIndex: "1",
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
    {
      id: "2",
      first_name: "Jane",
      last_name: "Smith",
      email: "jane@mail.com",
      phone: "+380000000001",
      status: "in_progress",
      comment: "Waiting for reply",
      orderIndex: "2",
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
    {
      id: "3",
      first_name: "Michael",
      last_name: "Brown",
      email: "michael@mail.com",
      phone: "+380000000002",
      status: "done",
      comment: "Deal closed",
      orderIndex: "3",
      createdBy: users.u2,
      createdAt: new Date().toISOString(),
    },
    {
      id: "4",
      first_name: "Emily",
      last_name: "Johnson",
      email: "emily@mail.com",
      phone: "+380000000003",
      status: "new",
      comment: "Requested demo",
      orderIndex: "4",
      createdBy: users.u2,
      createdAt: new Date().toISOString(),
    },
    {
      id: "5",
      first_name: "Daniel",
      last_name: "Wilson",
      email: "daniel@mail.com",
      phone: "+380000000004",
      status: "in_progress",
      comment: "Negotiation stage",
      orderIndex: "5",
      createdBy: users.u3,
      createdAt: new Date().toISOString(),
    },
    {
      id: "6",
      first_name: "Olivia",
      last_name: "Martinez",
      email: "olivia@mail.com",
      phone: "+380000000005",
      status: "new",
      comment: "Left contact form",
      orderIndex: "6",
      createdBy: users.u3,
      createdAt: new Date().toISOString(),
    },
    {
      id: "7",
      first_name: "William",
      last_name: "Anderson",
      email: "william@mail.com",
      phone: "+380000000006",
      status: "done",
      comment: "Signed contract",
      orderIndex: "7",
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
    {
      id: "8",
      first_name: "Sophia",
      last_name: "Lee",
      email: "sophia@mail.com",
      phone: "+380000000007",
      status: "in_progress",
      comment: "Preparing proposal",
      orderIndex: "8",
      createdBy: users.u2,
      createdAt: new Date().toISOString(),
    },
    {
      id: "9",
      first_name: "James",
      last_name: "Walker",
      email: "james@mail.com",
      phone: "+380000000008",
      status: "new",
      comment: "Cold lead",
      orderIndex: "9",
      createdBy: users.u3,
      createdAt: new Date().toISOString(),
    },
    {
      id: "10",
      first_name: "Isabella",
      last_name: "Harris",
      email: "isabella@mail.com",
      phone: "+380000000009",
      status: "done",
      comment: "Repeat client",
      orderIndex: "10",
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
  ]);
};
