import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { GlobalStyles } from "@mui/system";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "B2B crm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-mui-color-scheme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body className="flex flex-col flex-1 min-h-full">
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <GlobalStyles styles="@layer theme, base, mui, components, utilities;" />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
